### ISSUE TITLE
Delete undo

### ISSUE THREAD

**Issue by gdcl** [tconfrey/BrainTool#1]
Great project - i like the direction you're headed. 
In the chrome extension window, for users doing changes in there, the delete icon is dangerously close to the open/close icon, so it's easy to misclick and delete something. After deleting, there is no undo, unless i'm missing something. 
Keep up the good work - this is promising.

**Comment by tconfrey** [comment]
Thanks @gdcl , good suggestions. I don't have an undo RN but will put it on my list. I'll also reposition the buttons on the next iteration. Probably the TODO button is least used and can go next to Delete. 
Also note that I do warn on any deletion of a tag so you can only loose a single link by mistake. Also FYI, GDrive does a good job of keeping all previous versions, so worst case you can restore a previous version of the BrainTool.org file from there.
Tony

**Comment by tconfrey** [comment]
Closing this as undo have been implemented for quite a while. It did not work to move the buttons but I did add more space between Delete and other actions
