### ISSUE TITLE
Filing to multiple new subtrees fails

### ISSUE THREAD

**Issue by mediapathic** [tconfrey/BrainTool#10]
I have a first level header `Area` which does not contain a header `Norse`. I save a bookmark with the path `Area:Norse:Language`. I would expect this to create a subheading `Norse` and within that create a subheading `Language`. Instead, it created a new top level heading `Area:Norse` and beneath that a second level heading `Language`. I include a screenshot to illustrate if that's not clear. 

<img width="500" alt="Screen Shot 2021-05-09 at 18 00 03" src="https://user-images.githubusercontent.com/144331/117593382-6189ea00-b0f0-11eb-9e8c-d7656e78016e.png">

(also hi @tconfrey , I figured this would be more efficient than sending another email!)

**Comment by tconfrey** [comment]
Thanks Steen, yes this is a good bug! I don't actually support more than two levels of new node creation at the top level right now. I took a shortcut with the initial implementation and this is a good reminder to circle back to it. That said, I would have expected the result to be Norse at the top level and then Language under it, which would make it easy to just move the Norse subtree under Area. I'll put this on my backlog.

**Comment by tconfrey** [comment]
With the most recent 0.9.9 release this is fixed. Adding 
Animal:Vertebrate:Mammal:Carnivore:Canid:Dog:Hound:Beagle as topic will create 8 levels of topic if they don't already exist
