### ISSUE TITLE
Support tab groups

### ISSUE THREAD

**Issue by gdcl** [tconfrey/BrainTool#2]
Tab groups seem to be a perfect match for what you built here. Consider being able to state in a node in the tree whether you can it grouped under a window, or in a tab group. Both would be useful and it would bring down the total nr of windows if you want to bring up a whole set of pages at once. 
Great project.

**Comment by tconfrey** [comment]
Hi @gdcl,
First, I'm sorry I missed your issues earlier, I use git on the command line and didn't think to monitor for issues posted on github.

You are completely correct that tab groups are a good match for the BrainTool ui! I got a lot of good comments and complaints about the way BT handles Chrome windows and have been working on improvements for the last few weeks. I'm close to completion and hope to have a version out to some alpha testers early next week. I'll post details on the [discussion group](https://groups.google.com/u/2/g/braintool-discussion) and you can LMK if you want in.

Tony

**Comment by tconfrey** [comment]
Hi @gdcl ,
The new 0.7.0 version of BrainTool that just went live in the Store supports a global preference for whether new tabs should open in dedicated windows per tag (the initial model), or tab groups per tag, or just as a new tab in the default working browser window.

At some later point it may make sense to allow this mapping to be set on a per-tag basis but for now I think the global setting does the job. I'd love your feedback on the result.

NB one issue I have is that the Chrome Tab Grouping api is not yet fully functional in production Chrome so I can't name the tab groups appropriately. The upcoming 89 version of Chrome is meant to address this at which point I'll name the tab groups appropriately.

Regards,
Tony

**Comment by TBG-FR** [comment]
> Hi @gdcl , The new 0.7.0 version of BrainTool that just went live in the Store supports a global preference for whether new tabs should open in dedicated windows per tag (the initial model), or tab groups per tag, or just as a new tab in the default working browser window.
> 
> [...]

Is this global preference still a thing ? I can't find it
