### ISSUE TITLE
ambiguous error message

### ISSUE THREAD

**Issue by ComedyTomedy** [tconfrey/BrainTool#20]
Having got out of sync with GDrive, I got the following message on another laptop:

"There's a newer braintool.org file on gdrive - overwrite?"

I'm overjoyed to find that my data hasn't been clobbered, but if I click OK, it's not clear whether this will overwrite local with remote, or vice versa. The message needs to be more explicit.

**Comment by tconfrey** [comment]
Thanks for the feedback. Should be improved in 1.0
