### ISSUE TITLE
Is it possible for Braintool to support store file in Dropbox?

### ISSUE THREAD

**Issue by MatsuriMW** [tconfrey/BrainTool#22]
Or support the local file saving on Brave(another chromium browser), either will do. 
They're both very important to me.

**Comment by emeinhardt** [comment]
Yeah, out of curiosity, why is local file saving not supported on other chromium browsers besides Chrome itself?

**Comment by ebaker** [comment]
I ran into the same issue with local file saving on Brave @MatsuriMW . Local file saving can be enabled with the `brave://flags/#file-system-access-api` flag. See https://github.com/brave/brave-browser/issues/20563 for more info. Seems to be working for me with BrainTool once flag was enabled.

**Comment by MatsuriMW** [comment]
> I ran into the same issue with local file saving on Brave @MatsuriMW . Local file saving can be enabled with the `brave://flags/#file-system-access-api` flag. See [brave/brave-browser#20563](https://github.com/brave/brave-browser/issues/20563) for more info. Seems to be working for me with BrainTool once flag was enabled.

OH MY GOD, YOU ARE GENIUS! Can't thank you enough!

**Comment by tconfrey** [comment]
Hi @ebaker, thanks for the tip! I'm finally getting back to putting time into BrainTool and usually develop and test it on Brave (I use Chrome as my working browser and BT tree). Not having local file saving has been a PIA. I'm gonna add this to a FAQ and close the issue.

**Comment by ebaker** [comment]
Thank you @tconfrey ! I also sent you an email about something similar but unrelated to this specifically. I'll re-send the email in 24 hours if I don't hear from you to get to the top of your inbox. No rush to get back to me and I really appreciate everything you've built. Being a frontend developer, and fellow emacs enthusiast, I might be able to help contribute in the future. Currently I'm at capacity though, it's great to hear from you and I'm really excited to learn more about what you're working on with BrainTool now. Again, thank you so much for all your work on BrainTool!
