### ISSUE TITLE
Some sections of UI cut off

### ISSUE THREAD

**Issue by loopernow** [tconfrey/BrainTool#27]
See screenshots:

![image](https://user-images.githubusercontent.com/11263913/218333982-be400b85-c159-488e-af0b-ffebc68833da.png)

![image](https://user-images.githubusercontent.com/11263913/218333997-584de9b0-81e9-4fd3-bd0e-47f776393793.png)

I tried using Ctrl-+ and Ctrl-- to see if that would make more of the cut-off text visible but it did not.

This is on Windows 10 and Microsoft Edge 110.0.1587.41.

**Comment by tconfrey** [comment]
fixed in Braintool 1.0.
