### ISSUE TITLE
Selection of child topics within BrainTool Saver does not seem to work in all cases

### ISSUE THREAD

**Issue by chrigehr** [tconfrey/BrainTool#28]
Hi,

I have seen a "surprising" behaviour within the "BrainTool Saver", that might also be a bug.
If you have 
- child topics where the one child topic name is a prefix of another child topic name
- or one child topic name is a substring within another child topic name

you are not able to correctly select one of them. The BrainTool Saver seems to choose one of the entries and no entry is visually selected in the tree view, regardless of "clicks" in the tree view.

What is working though is the incremental search using the text field. This correctly shows all matching entries and you can select the one you want.

Braintool Version: 0.99
Chrome Version: Version 111.0.5563.110 (Official Build) (64-bit)

Best regards,
Chris

**Comment by tconfrey** [comment]
Thanks for the bug report. This issue is fixed in the 1.0 version of BrainTool which was released recently.
