### ISSUE TITLE
HTML tags in bookmarked titles not sanitized, displaying as actual elements in the UI

### ISSUE THREAD

**Issue by miguelsm** [tconfrey/BrainTool#31]
When saving a page which title contains some html, the browser extension fails to properly sanitize the title, resulting in the HTML tags being displayed as actual elements in the UI.

Example page: https://news.ycombinator.com/item?id=37163784 - with title: "Why does email development have to suck? – Explaining all the &lt;tr&gt;'s and &lt;td&gt;'s | Hacker News"

Results in:

![Screenshot 2024-03-10 21 59 19](https://github.com/tconfrey/BrainTool/assets/693520/1f3601e4-0dac-4037-8a4b-f3640a9172bf)

![Screenshot 2024-03-10 22 00 30](https://github.com/tconfrey/BrainTool/assets/693520/f8eef933-79b1-4ef8-a6a0-a9dcd907f22d)

**Comment by tconfrey** [comment]
Thanks for the bug report. This issue is fixed in the 1.0 release of BrainTool which is now up on the Chrome and Edge app stores.
