### ISSUE TITLE
Deleting a link navigates in "browser tab" setting

### ISSUE THREAD

**Issue by nmay231** [tconfrey/BrainTool#33]
Deleting a topic in the topic list will navigate to the page just deleted, which I assume makes sense when BT is in a side panel, but is very disorienting when it is a browser tab.

As a side-note, I might use the side panel setting, but the automatic window resizing simply doesn't work on linux (Ubuntu 22.04 Wayland). It just unmaximizes the browser window; the BT side panel does correctly become a side panel.

**Comment by tconfrey** [comment]
Thanks for the suggestion. The 1.0.2 release which just went live on the Chrome Store addresses both of these issues. BT no longer navigates to an open tab for a deleted item if it (BT) is running in a tab. The automatic window resizing only happened on first launch, but in any case when opening the side panel BT no longer unmaximizes the browser window. At least on my Mac this leads to a potentially disconcerting switch to a different desktop to show the side panel but I don't think there's a better approach.

Cheers,
Tony
