### ISSUE TITLE
Stuck.  Removed extension and reinstalled to resolve

### ISSUE THREAD

**Issue by jjcelerity** [tconfrey/BrainTool#8]
Braintool was stuck authenticating.  Tried exiting Chrome and restarting.  Rebooted PC and restated.  Neither resolved the problem.  Uninstalled the extension and re-installed.  That solved the issues.

**Comment by tconfrey** [comment]
Thanks @jjcelerity, sorry I'm just seeing this now after realizing today that people had been posting issues on GitHub. 

A number of people had problems with the GDrive authentication in the first version of BrainTool. In the subsequent releases I tightened up the code and provided better error handling, so hopefully this is not still an problem (I have not been hearing that it is). I'll leave the issue open for now.

Cheers,
Tony

**Comment by tconfrey** [comment]
I'm gonna close this one out. I've made several round of improvements to the GDrive auth.
